package eccrm.base.role.domain;

import eccrm.base.tenement.domain.CrmBaseDomain;
import eccrm.base.user.domain.User;

/**
 * Generated by miles on 2014-07-21.
 */

public class RoleUser extends CrmBaseDomain {

    private Role role;
    private User user;


    public RoleUser() {
    }

    public RoleUser(String userId, String roleId) {
        this.role = new Role();
        this.user = new User();
        role.setId(roleId);
        user.setId(userId);
    }

    public RoleUser(User user, Role role) {
        this.role = role;
        this.user = user;
    }

    public Role getRole() {
        return role;
    }

    public void setRole(Role role) {
        this.role = role;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

}
