package eccrm.base.role.domain;

import eccrm.base.menu.domain.Menu;
import eccrm.base.tenement.domain.CrmBaseDomain;

/**
 * 角色对应的资源（菜单/操作点）
 * Generated by miles on 2014-07-21.
 */

public class RoleResource extends CrmBaseDomain {

    private Role role;
    private Menu menu;
    private Integer sequenceNo;

    public RoleResource() {
    }

    public RoleResource(String roleId, String menuId) {
        this.role = new Role();
        this.menu = new Menu();
        role.setId(roleId);
        menu.setId(menuId);
    }


    public Role getRole() {
        return role;
    }

    public void setRole(Role role) {
        this.role = role;
    }

    public Menu getMenu() {
        return menu;
    }

    public void setMenu(Menu menu) {
        this.menu = menu;
    }

    public Integer getSequenceNo() {
        return sequenceNo;
    }

    public void setSequenceNo(Integer sequenceNo) {
        this.sequenceNo = sequenceNo;
    }
}
