package eccrm.base.role.domain;

import eccrm.base.tenement.domain.CrmBaseDomain;
import eccrm.base.user.domain.Group;

/**
 * Generated by miles on 2014-07-21.
 */

public class RoleGroup extends CrmBaseDomain {

    private Role role;
    private Group group;

    public RoleGroup() {
    }

    public RoleGroup(String roleId, String groupId) {
        this.role = new Role();
        role.setId(roleId);
        this.group = new Group();
        group.setId(groupId);

    }

    public RoleGroup(Role role, Group group) {
        this.role = role;
        this.group = group;
    }

    public Role getRole() {
        return role;
    }

    public void setRole(Role role) {
        this.role = role;
    }

    public Group getGroup() {
        return group;
    }

    public void setGroup(Group group) {
        this.group = group;
    }
}
