package eccrm.base.position.bo;


import eccrm.base.position.domain.Position;

/**
 * Generated by chenl on 2014-10-11.
 */

public class PositionBo extends Position {

    /**
     * 岗位分类ID
     */
    private String type;

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }
}
