package eccrm.base.position.bo;


import eccrm.base.position.domain.PositionParam;

/**
 * Generated by chenl on 2014-10-20.
 */

public class PositionParamBo extends PositionParam {
    private String positionName;

    public String getPositionName() {
        return positionName;
    }

    public void setPositionName(String positionName) {
        this.positionName = positionName;
    }
}
