package eccrm.base.employee.bo;


import eccrm.base.employee.domain.BlankList;

/**
* Generated by liuxq on 2014-10-22.
*/

public class BlankListBo extends BlankList {
    /**
     * 员工姓名
     */
    private String empName;
    /**
     * 员工号
     */
    private String empNo;
    /**
     * 电话号
     */
    private String tel;

    /**
     * 机构ID
     */
    private String orgId;
    private String orgName;
    private String extensionNumber;
    /**
     * 系统
     */
    private String param;

    public String getExtensionNumber() {
        return extensionNumber;
    }

    public void setExtensionNumber(String extensionNumber) {
        this.extensionNumber = extensionNumber;
    }

    public String getEmpName() {
        return empName;
    }

    public void setEmpName(String empName) {
        this.empName = empName;
    }

    public String getEmpNo() {
        return empNo;
    }

    public void setEmpNo(String empNo) {
        this.empNo = empNo;
    }

    public String getTel() {
        return tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getOrgId() {
        return orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    public String getParam() {
        return param;
    }

    public void setParam(String param) {
        this.param = param;
    }

    public String getOrgName() {
        return orgName;
    }

    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }
}
