package eccrm.base.contact.vo;

import com.ycrl.base.common.CommonVo;

import java.util.Date;

/**
 * Generated by chenl on 2014-09-22.
 */

public class ContactVo extends CommonVo {

    private String resourceType;//客户类型
    private String resourceTypeName;//客户类型
    private String resourceId;//客户ID
    private String resourceName;//客户姓名
    private String linkmanId;//联系人ID
    private String linkmanName;//联系人姓名
    private String contactType;//联系类型
    private String contactID;//联系类型ID
    private String country;//国家
    private String province;//省
    private String city;//市
    private String district;//区
    private String address;//国家
    private String postCode;//邮编
    private Date startDatetime;//开始时间
    private Date endDatetime;//结束时间
    private String contactItem;//联络事项
    private String contactItemName;//联络事项
    private String contactDirect;//联络方向
    private String contactDirectName;//联络方向
    private String contactMethod;//联络方式
    private String contactMethodName;//联络方式
    private String content;//描述
    private String resultType;//结果类型
    private String resultTypeName;//结果类型
    private String remark;//处理说明
    //    private String status;//状态
    private String nextLinkmanId;//联系人ID
    private String nextLinkmanName;//联系人姓名
    private String nextContactType;//联系类型
    private String nextCountry;//国家
    private String nextProvince;//省
    private String nextCity;//市
    private String nextDistrict;//区
    private String nextAddress;//国家
    private String nextPostCode;//邮编
    private Date nextTime;//结束时间
    private String code;//编号
    private String satisfaction;//满意度

    //节点
    private String ndoeId;
    private String ndoeName;

    private String hour;
    //录音ID
    private String niceId;
    //录音地址
    private String niceUrl;

    private String stageId;
    private String stageName;
    private Integer isBespeak;
    private String bespeakPhone;

    public String getStageId() {
        return stageId;
    }

    public void setStageId(String stageId) {
        this.stageId = stageId;
    }

    public String getStageName() {
        return stageName;
    }

    public void setStageName(String stageName) {
        this.stageName = stageName;
    }

    public Integer getIsBespeak() {
        return isBespeak;
    }

    public void setIsBespeak(Integer isBespeak) {
        this.isBespeak = isBespeak;
    }

    public String getBespeakPhone() {
        return bespeakPhone;
    }

    public void setBespeakPhone(String bespeakPhone) {
        this.bespeakPhone = bespeakPhone;
    }

    public String getHour() {
        return hour;
    }

    public void setHour(String hour) {
        this.hour = hour;
    }

    public String getNiceId() {
        return niceId;
    }

    public void setNiceId(String niceId) {
        this.niceId = niceId;
    }

    public String getNiceUrl() {
        return niceUrl;
    }

    public void setNiceUrl(String niceUrl) {
        this.niceUrl = niceUrl;
    }

    public String getNdoeId() {
        return ndoeId;
    }

    public void setNdoeId(String ndoeId) {
        this.ndoeId = ndoeId;
    }

    public String getNdoeName() {
        return ndoeName;
    }

    public void setNdoeName(String ndoeName) {
        this.ndoeName = ndoeName;
    }

    public String getSatisfaction() {
        return satisfaction;
    }

    public void setSatisfaction(String satisfaction) {
        this.satisfaction = satisfaction;
    }

    public String getResourceTypeName() {
        return resourceTypeName;
    }

    public void setResourceTypeName(String resourceTypeName) {
        this.resourceTypeName = resourceTypeName;
    }

    public String getContactItemName() {
        return contactItemName;
    }

    public void setContactItemName(String contactItemName) {
        this.contactItemName = contactItemName;
    }

    public String getContactDirectName() {
        return contactDirectName;
    }

    public void setContactDirectName(String contactDirectName) {
        this.contactDirectName = contactDirectName;
    }

    public String getContactMethodName() {
        return contactMethodName;
    }

    public void setContactMethodName(String contactMethodName) {
        this.contactMethodName = contactMethodName;
    }

    public String getResultTypeName() {
        return resultTypeName;
    }

    public void setResultTypeName(String resultTypeName) {
        this.resultTypeName = resultTypeName;
    }

    public String getContactID() {
        return contactID;
    }

    public void setContactID(String contactID) {
        this.contactID = contactID;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getContactMethod() {
        return contactMethod;
    }

    public void setContactMethod(String contactMethod) {
        this.contactMethod = contactMethod;
    }

    public String getResourceType() {
        return resourceType;
    }

    public void setResourceType(String resourceType) {
        this.resourceType = resourceType;
    }

    public String getResourceId() {
        return resourceId;
    }

    public void setResourceId(String resourceId) {
        this.resourceId = resourceId;
    }

    public String getResourceName() {
        return resourceName;
    }

    public void setResourceName(String resourceName) {
        this.resourceName = resourceName;
    }

    public String getLinkmanId() {
        return linkmanId;
    }

    public void setLinkmanId(String linkmanId) {
        this.linkmanId = linkmanId;
    }

    public String getLinkmanName() {
        return linkmanName;
    }

    public void setLinkmanName(String linkmanName) {
        this.linkmanName = linkmanName;
    }

    public String getContactType() {
        return contactType;
    }

    public void setContactType(String contactType) {
        this.contactType = contactType;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getProvince() {
        return province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getDistrict() {
        return district;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPostCode() {
        return postCode;
    }

    public void setPostCode(String postCode) {
        this.postCode = postCode;
    }

    public Date getStartDatetime() {
        return startDatetime;
    }

    public void setStartDatetime(Date startDatetime) {
        this.startDatetime = startDatetime;
    }

    public Date getEndDatetime() {
        return endDatetime;
    }

    public void setEndDatetime(Date endDatetime) {
        this.endDatetime = endDatetime;
    }

    public String getContactItem() {
        return contactItem;
    }

    public void setContactItem(String contactItem) {
        this.contactItem = contactItem;
    }

    public String getContactDirect() {
        return contactDirect;
    }

    public void setContactDirect(String contactDirect) {
        this.contactDirect = contactDirect;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getResultType() {
        return resultType;
    }

    public void setResultType(String resultType) {
        this.resultType = resultType;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

//    public String getStatus() {
//        return status;
//    }
//
//    public void setStatus(String status) {
//        this.status = status;
//    }

    public String getNextLinkmanId() {
        return nextLinkmanId;
    }

    public void setNextLinkmanId(String nextLinkmanId) {
        this.nextLinkmanId = nextLinkmanId;
    }

    public String getNextLinkmanName() {
        return nextLinkmanName;
    }

    public void setNextLinkmanName(String nextLinkmanName) {
        this.nextLinkmanName = nextLinkmanName;
    }

    public String getNextContactType() {
        return nextContactType;
    }

    public void setNextContactType(String nextContactType) {
        this.nextContactType = nextContactType;
    }

    public String getNextCountry() {
        return nextCountry;
    }

    public void setNextCountry(String nextCountry) {
        this.nextCountry = nextCountry;
    }

    public String getNextProvince() {
        return nextProvince;
    }

    public void setNextProvince(String nextProvince) {
        this.nextProvince = nextProvince;
    }

    public String getNextCity() {
        return nextCity;
    }

    public void setNextCity(String nextCity) {
        this.nextCity = nextCity;
    }

    public String getNextDistrict() {
        return nextDistrict;
    }

    public void setNextDistrict(String nextDistrict) {
        this.nextDistrict = nextDistrict;
    }

    public String getNextAddress() {
        return nextAddress;
    }

    public void setNextAddress(String nextAddress) {
        this.nextAddress = nextAddress;
    }

    public String getNextPostCode() {
        return nextPostCode;
    }

    public void setNextPostCode(String nextPostCode) {
        this.nextPostCode = nextPostCode;
    }

    public Date getNextTime() {
        return nextTime;
    }

    public void setNextTime(Date nextTime) {
        this.nextTime = nextTime;
    }

}
