package eccrm.base.org.bo;


import eccrm.base.org.domain.Organization;

/**
 * Generated by yanhx on 2014-10-13.
 */

public class OrganizationBo extends Organization {
    /**
     * 如果该值为true，则表示只查询根
     */
    private Boolean root;

    public Boolean getRoot() {
        return root;
    }

    public void setRoot(Boolean root) {
        this.root = root;
    }
}
