package eccrm.base.org.service;


import com.ycrl.core.beans.BeanWrapper;
import com.ycrl.core.pager.PageVo;
import eccrm.base.org.bo.OrgPositionBo;
import eccrm.base.org.domain.OrgPosition;
import eccrm.base.org.vo.OrgPositionVo;
import eccrm.base.position.vo.PositionVo;

import java.util.List;

/**
 * Generated by yanhx on 2014-10-13.
 */

public interface OrgPositionService extends BeanWrapper<OrgPosition, OrgPositionVo> {

    String save(OrgPosition orgPosition) throws Exception;

    void update(OrgPosition orgPosition);

    PageVo query(OrgPositionBo bo);

    /**
     * 查询一个组织机构下的所有的岗位信息
     * <p>注意：只返回岗位的id和名称</p>
     *
     * @param orgId 岗位id
     */
    List<PositionVo> queryByOrgId(String orgId);

    /**
     * 分页查询一个组织机构下的岗位信息
     *
     * @param orgId 岗位id
     */
    PageVo pageQueryByOrgId(String orgId);

    OrgPositionVo findById(String id);

    void deleteByIds(String... ids);

    void deleteByRoleId(OrgPositionBo bo);

    List<PositionVo> queryAll(OrgPositionBo bo);

    public PageVo queryByOrgIdforTree(String orgId);

    /**
     * 查询所有具有岗位的组织机构的id集合
     *
     * @return 组织机构id集合
     */
    List<String> whoHasPosition();


    /**
     * 查询指定类型下状态为有效的岗位
     *
     * @param code 编号
     */
    OrgPositionVo queryValidByCode(String code);

}
