package eccrm.base.employee.service.impl;

import eccrm.base.employee.bo.EmployeePositionBo;
import eccrm.base.employee.dao.EmployeePositionDao;
import eccrm.base.employee.domain.EmployeePosition;
import eccrm.base.employee.service.EmployeePositionService;
import eccrm.base.employee.vo.EmployeePositionVo;
import com.ycrl.core.beans.BeanHelper;
import com.ycrl.core.pager.PageVo;
import org.springframework.beans.BeanUtils;
import org.springframework.stereotype.Service;

import javax.annotation.Resource;
import java.util.List;

/**
* Generated by yanhx on 2014-10-13.
*/

@Service("employeePositionService")
public class EmployeePositionServiceImpl implements EmployeePositionService {
    @Resource
    private EmployeePositionDao employeePositionDao;

    @Override
    public String save(EmployeePosition employeePosition) {
        String id = employeePositionDao.save(employeePosition);
        return id;
    }

    @Override
    public void update(EmployeePosition employeePosition) {
        employeePositionDao.update(employeePosition);
    }

    @Override
    public PageVo query(EmployeePositionBo bo) {
        PageVo vo = new PageVo();
        Long total = employeePositionDao.getTotal(bo);
        vo.setTotal(total);
        if (total == 0) return vo;
        List<EmployeePosition> employeePositions = employeePositionDao.query(bo);
        vo.setData(BeanHelper.wrapList(employeePositions, this));
        return vo;
    }

    @Override
    public EmployeePositionVo findById(String id) {
        return wrap(employeePositionDao.findById(id));
    }

    @Override
    public List<EmployeePosition> findByRuleId(String id) {
        EmployeePositionBo employeePositionTempBo=new EmployeePositionBo();
        employeePositionTempBo.setRoleId(id);
        return employeePositionDao.query(employeePositionTempBo);
    }
    @Override
    public void deleteByIds(String... ids) {
        if (ids == null || ids.length == 0) return;
        for (String id : ids) {
            employeePositionDao.deleteById(id);
        }
    }


    public EmployeePositionVo wrap(EmployeePosition employeePosition){
        if (employeePosition == null) return null;
        EmployeePositionVo vo = new EmployeePositionVo();
        BeanUtils.copyProperties(employeePosition, vo);
        return vo;
    }
}
