package eccrm.base.employee.service.impl;

import com.ycrl.core.beans.BeanWrapBuilder;
import com.ycrl.core.beans.BeanWrapCallback;
import com.ycrl.core.pager.PageVo;
import eccrm.base.employee.bo.EmployeeBo;
import eccrm.base.employee.dao.BlankListDao;
import eccrm.base.employee.dao.EmployeeDao;
import eccrm.base.employee.domain.Employee;
import eccrm.base.employee.service.ContactType;
import eccrm.base.employee.service.EmployeeOrgRelService;
import eccrm.base.employee.service.EmployeeService;
import eccrm.base.employee.vo.EmployeeVo;
import eccrm.base.parameter.service.ParameterContainer;
import eccrm.base.position.bo.PositionEmpBo;
import eccrm.base.position.dao.PositionDao;
import eccrm.base.position.dao.PositionEmpDao;
import eccrm.base.position.domain.PositionEmp;
import eccrm.base.position.service.PositionEmpService;
import org.springframework.stereotype.Service;

import javax.annotation.Resource;
import java.util.ArrayList;
import java.util.List;

/**
 * Generated by yanhx on 2014-10-13.
 */

@Service("employeeServices")
public class EmployeeServiceImpl implements EmployeeService, BeanWrapCallback<Employee, EmployeeVo> {
    @Resource
    private EmployeeDao employeesDao;
    @Resource
    private PositionEmpDao positionEmpDao;
    @Resource
    private EmployeeOrgRelService employeeOrgRelService;
    @Resource
    private PositionEmpService positionEmpService;
    @Resource
    private PositionDao positionDao;

    @Resource
    private BlankListDao blankListDao;

    @Override
    public String save(Employee employee) {
        String id = employeesDao.save(employee);
        return id;
    }

    @Override
    public void update(Employee employee) {
        employeesDao.update(employee);
    }

    @Override
    public PageVo query(EmployeeBo bo) {
        PageVo vo = new PageVo();
        Long total = employeesDao.getTotal(bo);
        vo.setTotal(total);
        if (total == 0) return vo;
        List<Employee> employees = employeesDao.query(bo);
        vo.setData(BeanWrapBuilder.newInstance().setCallback(this).wrapList(employees, EmployeeVo.class));
        return vo;
    }

    @Override
    public PageVo queryValid(EmployeeBo bo) {
        PageVo vo = new PageVo();
        if (bo == null) {
            bo = new EmployeeBo();
        }
        bo.setValid(true);
        Long total = employeesDao.getTotal(bo);
        vo.setTotal(total);
        if (total == 0) return vo;
        List<Employee> employees = employeesDao.query(bo);
        vo.setData(BeanWrapBuilder.newInstance().setCallback(this).wrapList(employees, EmployeeVo.class));
        return vo;
    }

    @Override
    public List<EmployeeVo> querys(EmployeeBo bo) {
        List<PositionEmp> positionEmps = new ArrayList<PositionEmp>();
        List<Employee> employees = new ArrayList<Employee>();
        String ids = null;
        if (bo.getOrgId() != null || bo.getPositionId() != null) {
            PositionEmpBo positionEmpBo = new PositionEmpBo();
            if (bo.getOrgId() != null) {
                positionEmpBo.setOrgId(bo.getOrgId());
            }
            if (bo.getPositionId() != null) {
                positionEmpBo.setPositionId(bo.getPositionId());
            }
            positionEmps = positionEmpDao.query(positionEmpBo);
            if (positionEmps != null) {
                if (positionEmps.size() > 0) {
                    for (int i = 0; i < positionEmps.size(); i++) {
                        if (i != positionEmps.size() - 1) {
                            ids = "'" + positionEmps.get(i).getEmpId() + "',";
                        } else {
                            ids = "'" + positionEmps.get(i).getEmpId() + "'";
                        }
                    }
                    employees = employeesDao.querys(bo, ids);

                }
            } else {
                employees = null;
            }

        } else {
            employees = employeesDao.query(bo);

        }
        return BeanWrapBuilder.newInstance().setCallback(this)
                .wrapList(employees, EmployeeVo.class);
    }

    @Override
    public EmployeeVo findById(String id) {
        return BeanWrapBuilder.newInstance().setCallback(this)
                .wrap(employeesDao.findById(id), EmployeeVo.class);
    }



    @Override
    public List<Employee> queryByOrgId(String id) {
        List<Employee> employeeList = employeeOrgRelService.findByOrgId(id);
        return employeeList;
    }

    @Override
    public List<EmployeeVo> queryByRuleId(String id, String orgId) {
        List<EmployeeVo> employeeList = positionEmpService.findByEmployee(id, orgId);
        return employeeList;
    }

    @Override
    public void deleteByIds(String... ids) {
        if (ids == null || ids.length == 0) return;
        for (String id : ids) {
            employeesDao.deleteById(id);
        }
    }


    @Override
    public void doCallback(Employee employee, EmployeeVo vo) {
        ParameterContainer parameterContainer = ParameterContainer.getInstance();
        // 职务
        vo.setDutyName(parameterContainer.getBusinessName(ContactType.BP_ZHIW, vo.getDuty()));
        // 工作类型
        vo.setWorkTypeName(parameterContainer.getBusinessName(ContactType.BP_EMPTYPE, vo.getWorkType()));
        // 状态
        vo.setStatusName(parameterContainer.getSystemName(ContactType.CONT_TYPE_STATUS, vo.getStatus()));
        // 性别
        vo.setGenderName(parameterContainer.getBusinessName("BP_SEX", employee.getGender()));
        // 民族
        vo.setNationName(parameterContainer.getBusinessName("BP_NATION", employee.getNation()));
    }

    @Override
    public boolean isExists(String rtxId) {
        return employeesDao.isExists(rtxId);
    }

    @Override
    public String findNameById(String employeeId) {
        return employeesDao.findNameById(employeeId);
    }

    @Override
    public Employee findById2(String employID) {
        return employeesDao.findById(employID);
    }


    @Override
    public PageVo permissionPageQuery(EmployeeBo bo) {
        if (bo == null) {
            bo = new EmployeeBo();
        }
        bo.setPermission(true);
        return query(bo);
    }

}
