package eccrm.base.employee.service.impl;

import eccrm.base.employee.bo.EmployeeOrgRelBo;
import eccrm.base.employee.dao.EmployeeOrgRelDao;
import eccrm.base.employee.domain.Employee;
import eccrm.base.employee.domain.EmployeeOrgRel;
import eccrm.base.employee.service.EmployeeOrgRelService;
import eccrm.base.employee.vo.EmployeeOrgRelVo;
import com.ycrl.core.beans.BeanHelper;
import com.ycrl.core.pager.PageVo;
import org.springframework.beans.BeanUtils;
import org.springframework.stereotype.Service;

import javax.annotation.Resource;
import java.util.ArrayList;
import java.util.List;

/**
* Generated by yanhx on 2014-10-13.
*/

@Service("employeeOrgRelService")
public class EmployeeOrgRelServiceImpl implements EmployeeOrgRelService {
    @Resource
    private EmployeeOrgRelDao employeeOrgRelDao;

    @Override
    public String save(EmployeeOrgRel employeeOrgRel) {
        String id = employeeOrgRelDao.save(employeeOrgRel);
        return id;
    }

    @Override
    public void update(EmployeeOrgRel employeeOrgRel) {
        employeeOrgRelDao.update(employeeOrgRel);
    }

    @Override
    public PageVo query(EmployeeOrgRelBo bo) {
        PageVo vo = new PageVo();
        Long total = employeeOrgRelDao.getTotal(bo);
        vo.setTotal(total);
        if (total == 0) return vo;
        List<EmployeeOrgRel> employeeOrgRels = employeeOrgRelDao.query(bo);
        vo.setData(BeanHelper.wrapList(employeeOrgRels, this));
        return vo;
    }

    @Override
    public EmployeeOrgRelVo findById(String id) {
        return wrap(employeeOrgRelDao.findById(id));
    }

    @Override
    public List<Employee> findByOrgId(String id) {
        List<Employee> employeeList=new ArrayList<Employee>();
        List<EmployeeOrgRel> employeeOrgRels=employeeOrgRelDao.queryByOrgId(id);
        if(employeeOrgRels!=null){
            for(EmployeeOrgRel e: employeeOrgRels){
                if(e.getEmplyuee()!=null){
                    employeeList.add(e.getEmplyuee());
                }
            }
        }
        return employeeList;
    }
    @Override
    public void deleteByIds(String... ids) {
        if (ids == null || ids.length == 0) return;
        for (String id : ids) {
            employeeOrgRelDao.deleteById(id);
        }
    }


    public EmployeeOrgRelVo wrap(EmployeeOrgRel employeeOrgRel){
        if (employeeOrgRel == null) return null;
        EmployeeOrgRelVo vo = new EmployeeOrgRelVo();
        BeanUtils.copyProperties(employeeOrgRel, vo);
        return vo;
    }
}
