package eccrm.base.employee.service.impl;

import eccrm.base.employee.domain.Employee;
import eccrm.base.employee.service.EmployeeOutsideService;
import eccrm.base.employee.service.EmployeeService;
import org.springframework.stereotype.Service;

import javax.annotation.Resource;
import java.util.List;

/**
 * Generated by yanhx on 2014-10-13.
 */

@Service("employeeOutsideService")
public class EmployeeOutsideServiceImpl implements EmployeeOutsideService {


    @Resource
    private  EmployeeService employeeServices;
    @Override
    public List<Employee> queryByOrgId(String id) {
        return employeeServices.queryByOrgId(id);
    }

}
