package eccrm.base.employee.vo;


import java.util.Date;

/**
* Generated by yanhx on 2014-10-13.
*/

public class EmployeeOrgRelTempVo {

    private String mdpGuid;
    private String employeeID;
    private String employeeCode;
    private String unitID;
    private String unitCode;
    private String isMainOrg;
    private Date mdpBatchTime;
    private String mdpOperationtype;
    private String mdpResult;

    public String getMdpGuid() {
        return mdpGuid;
    }

    public void setMdpGuid(String mdpGuid) {
        this.mdpGuid = mdpGuid;
    }

    public String getEmployeeID() {
        return employeeID;
    }

    public void setEmployeeID(String employeeID) {
        this.employeeID = employeeID;
    }

    public String getEmployeeCode() {
        return employeeCode;
    }

    public void setEmployeeCode(String employeeCode) {
        this.employeeCode = employeeCode;
    }

    public String getUnitID() {
        return unitID;
    }

    public void setUnitID(String unitID) {
        this.unitID = unitID;
    }

    public String getUnitCode() {
        return unitCode;
    }

    public void setUnitCode(String unitCode) {
        this.unitCode = unitCode;
    }

    public String getIsMainOrg() {
        return isMainOrg;
    }

    public void setIsMainOrg(String isMainOrg) {
        this.isMainOrg = isMainOrg;
    }

    public Date getMdpBatchTime() {
        return mdpBatchTime;
    }

    public void setMdpBatchTime(Date mdpBatchTime) {
        this.mdpBatchTime = mdpBatchTime;
    }

    public String getMdpOperationtype() {
        return mdpOperationtype;
    }

    public void setMdpOperationtype(String mdpOperationtype) {
        this.mdpOperationtype = mdpOperationtype;
    }

    public String getMdpResult() {
        return mdpResult;
    }

    public void setMdpResult(String mdpResult) {
        this.mdpResult = mdpResult;
    }


}
