package eccrm.base.employee.vo;


/**
* Generated by yanhx on 2014-10-13.
*/

public class EmployeeOrgRelVo {

    private String id;
    private String empId;
    private String orgId;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getEmpId() {
        return empId;
    }

    public void setEmpId(String empId) {
        this.empId = empId;
    }

    public String getOrgId() {
        return orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

}
