package eccrm.base.employee.vo;


import java.util.Date;

/**
* Generated by yanhx on 2014-10-13.
*/

public class EmployeeTempVo {


    private String mdpGuid;
    private Integer employeeID;
    private String employeeCode;
    private String employeeName;
    private String gender;
    private Date hireDate;
    private Date beginWorkDate;
    private Integer orgID;
    private String orgCode;
    private String orgName;
    private String unitID;
    private String unitCode;
    private String unitName;
    private Integer jobID;
    private String jobCode;
    private String jobName;
    private Date joinUnitDate;
    private String employeeStatus;
    private String isTransfer;
    private String status;
    private Date joinJobDate;
    private String weaveType;
    private Integer employeeOrder;
    private String jobLevel;
    private String isVerticalMangedType;
    private Date joinWdFirstDate;
    private String administrativeRank;
    private String isDimreport;
    private String isProbation;
    private String pinyin;
    private String username;
    private String isHotelProject;
    private String isIntern;
    private String isComprehensive;
    private String leaderSortNo;
    private String cadEmplyeeType;
    private String regin;
    private String oaEnabled;
    private String  hotelLevel;
    private String employeeStatusName;
    private String isVerticalMangedName;
    private String officeTel;
    private String employeeMobile;
    private String officeEmail;
    private String postcode;
    private Date reshuffleDate;
    private String unitFullPath;
    private String actualUnitID;
    private String RtxID;
    private String officeAddress;
    private String ncOrgID;
    private String ncDepID;
    private String ncPositionID;
    private String jobclass;
    private String heightestDegreeType;
    private String graduateDate;
    private String graduateSchool;
    private String specialty;
    private String birthday;
    private String mobile;
    private String cJishuxulie;
    private Date mdpBatchTime;
    private String mdpOperationtype;
    private String mdpResult;

    public String getMdpGuid() {
        return mdpGuid;
    }

    public void setMdpGuid(String mdpGuid) {
        this.mdpGuid = mdpGuid;
    }

    public Integer getEmployeeID() {
        return employeeID;
    }

    public void setEmployeeID(Integer employeeID) {
        this.employeeID = employeeID;
    }

    public String getEmployeeCode() {
        return employeeCode;
    }

    public void setEmployeeCode(String employeeCode) {
        this.employeeCode = employeeCode;
    }

    public String getEmployeeName() {
        return employeeName;
    }

    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public Date getHireDate() {
        return hireDate;
    }

    public void setHireDate(Date hireDate) {
        this.hireDate = hireDate;
    }

    public Date getBeginWorkDate() {
        return beginWorkDate;
    }

    public void setBeginWorkDate(Date beginWorkDate) {
        this.beginWorkDate = beginWorkDate;
    }

    public Integer getOrgID() {
        return orgID;
    }

    public void setOrgID(Integer orgID) {
        this.orgID = orgID;
    }

    public String getOrgCode() {
        return orgCode;
    }

    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    public String getOrgName() {
        return orgName;
    }

    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    public String getUnitID() {
        return unitID;
    }

    public void setUnitID(String unitID) {
        this.unitID = unitID;
    }

    public String getUnitCode() {
        return unitCode;
    }

    public void setUnitCode(String unitCode) {
        this.unitCode = unitCode;
    }

    public String getUnitName() {
        return unitName;
    }

    public void setUnitName(String unitName) {
        this.unitName = unitName;
    }

    public Integer getJobID() {
        return jobID;
    }

    public void setJobID(Integer jobID) {
        this.jobID = jobID;
    }

    public String getJobCode() {
        return jobCode;
    }

    public void setJobCode(String jobCode) {
        this.jobCode = jobCode;
    }

    public String getJobName() {
        return jobName;
    }

    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    public Date getJoinUnitDate() {
        return joinUnitDate;
    }

    public void setJoinUnitDate(Date joinUnitDate) {
        this.joinUnitDate = joinUnitDate;
    }

    public String getEmployeeStatus() {
        return employeeStatus;
    }

    public void setEmployeeStatus(String employeeStatus) {
        this.employeeStatus = employeeStatus;
    }

    public String getIsTransfer() {
        return isTransfer;
    }

    public void setIsTransfer(String isTransfer) {
        this.isTransfer = isTransfer;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Date getJoinJobDate() {
        return joinJobDate;
    }

    public void setJoinJobDate(Date joinJobDate) {
        this.joinJobDate = joinJobDate;
    }

    public String getWeaveType() {
        return weaveType;
    }

    public void setWeaveType(String weaveType) {
        this.weaveType = weaveType;
    }

    public Integer getEmployeeOrder() {
        return employeeOrder;
    }

    public void setEmployeeOrder(Integer employeeOrder) {
        this.employeeOrder = employeeOrder;
    }

    public String getJobLevel() {
        return jobLevel;
    }

    public void setJobLevel(String jobLevel) {
        this.jobLevel = jobLevel;
    }

    public String getIsVerticalMangedType() {
        return isVerticalMangedType;
    }

    public void setIsVerticalMangedType(String isVerticalMangedType) {
        this.isVerticalMangedType = isVerticalMangedType;
    }

    public Date getJoinWdFirstDate() {
        return joinWdFirstDate;
    }

    public void setJoinWdFirstDate(Date joinWdFirstDate) {
        this.joinWdFirstDate = joinWdFirstDate;
    }

    public String getAdministrativeRank() {
        return administrativeRank;
    }

    public void setAdministrativeRank(String administrativeRank) {
        this.administrativeRank = administrativeRank;
    }

    public String getIsDimreport() {
        return isDimreport;
    }

    public void setIsDimreport(String isDimreport) {
        this.isDimreport = isDimreport;
    }

    public String getIsProbation() {
        return isProbation;
    }

    public void setIsProbation(String isProbation) {
        this.isProbation = isProbation;
    }

    public String getPinyin() {
        return pinyin;
    }

    public void setPinyin(String pinyin) {
        this.pinyin = pinyin;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getIsHotelProject() {
        return isHotelProject;
    }

    public void setIsHotelProject(String isHotelProject) {
        this.isHotelProject = isHotelProject;
    }

    public String getIsIntern() {
        return isIntern;
    }

    public void setIsIntern(String isIntern) {
        this.isIntern = isIntern;
    }

    public String getIsComprehensive() {
        return isComprehensive;
    }

    public void setIsComprehensive(String isComprehensive) {
        this.isComprehensive = isComprehensive;
    }

    public String getLeaderSortNo() {
        return leaderSortNo;
    }

    public void setLeaderSortNo(String leaderSortNo) {
        this.leaderSortNo = leaderSortNo;
    }

    public String getCadEmplyeeType() {
        return cadEmplyeeType;
    }

    public void setCadEmplyeeType(String cadEmplyeeType) {
        this.cadEmplyeeType = cadEmplyeeType;
    }

    public String getRegin() {
        return regin;
    }

    public void setRegin(String regin) {
        this.regin = regin;
    }

    public String getOaEnabled() {
        return oaEnabled;
    }

    public void setOaEnabled(String oaEnabled) {
        this.oaEnabled = oaEnabled;
    }

    public String getHotelLevel() {
        return hotelLevel;
    }

    public void setHotelLevel(String hotelLevel) {
        this.hotelLevel = hotelLevel;
    }

    public String getEmployeeStatusName() {
        return employeeStatusName;
    }

    public void setEmployeeStatusName(String employeeStatusName) {
        this.employeeStatusName = employeeStatusName;
    }

    public String getIsVerticalMangedName() {
        return isVerticalMangedName;
    }

    public void setIsVerticalMangedName(String isVerticalMangedName) {
        this.isVerticalMangedName = isVerticalMangedName;
    }

    public String getOfficeTel() {
        return officeTel;
    }

    public void setOfficeTel(String officeTel) {
        this.officeTel = officeTel;
    }

    public String getEmployeeMobile() {
        return employeeMobile;
    }

    public void setEmployeeMobile(String employeeMobile) {
        this.employeeMobile = employeeMobile;
    }

    public String getOfficeEmail() {
        return officeEmail;
    }

    public void setOfficeEmail(String officeEmail) {
        this.officeEmail = officeEmail;
    }

    public String getPostcode() {
        return postcode;
    }

    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    public Date getReshuffleDate() {
        return reshuffleDate;
    }

    public void setReshuffleDate(Date reshuffleDate) {
        this.reshuffleDate = reshuffleDate;
    }

    public String getUnitFullPath() {
        return unitFullPath;
    }

    public void setUnitFullPath(String unitFullPath) {
        this.unitFullPath = unitFullPath;
    }

    public String getActualUnitID() {
        return actualUnitID;
    }

    public void setActualUnitID(String actualUnitID) {
        this.actualUnitID = actualUnitID;
    }

    public String getRtxID() {
        return RtxID;
    }

    public void setRtxID(String rtxID) {
        RtxID = rtxID;
    }

    public String getOfficeAddress() {
        return officeAddress;
    }

    public void setOfficeAddress(String officeAddress) {
        this.officeAddress = officeAddress;
    }

    public String getNcOrgID() {
        return ncOrgID;
    }

    public void setNcOrgID(String ncOrgID) {
        this.ncOrgID = ncOrgID;
    }

    public String getNcDepID() {
        return ncDepID;
    }

    public void setNcDepID(String ncDepID) {
        this.ncDepID = ncDepID;
    }

    public String getNcPositionID() {
        return ncPositionID;
    }

    public void setNcPositionID(String ncPositionID) {
        this.ncPositionID = ncPositionID;
    }

    public String getJobclass() {
        return jobclass;
    }

    public void setJobclass(String jobclass) {
        this.jobclass = jobclass;
    }

    public String getHeightestDegreeType() {
        return heightestDegreeType;
    }

    public void setHeightestDegreeType(String heightestDegreeType) {
        this.heightestDegreeType = heightestDegreeType;
    }

    public String getGraduateDate() {
        return graduateDate;
    }

    public void setGraduateDate(String graduateDate) {
        this.graduateDate = graduateDate;
    }

    public String getGraduateSchool() {
        return graduateSchool;
    }

    public void setGraduateSchool(String graduateSchool) {
        this.graduateSchool = graduateSchool;
    }

    public String getSpecialty() {
        return specialty;
    }

    public void setSpecialty(String specialty) {
        this.specialty = specialty;
    }

    public String getBirthday() {
        return birthday;
    }

    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getcJishuxulie() {
        return cJishuxulie;
    }

    public void setcJishuxulie(String cJishuxulie) {
        this.cJishuxulie = cJishuxulie;
    }

    public Date getMdpBatchTime() {
        return mdpBatchTime;
    }

    public void setMdpBatchTime(Date mdpBatchTime) {
        this.mdpBatchTime = mdpBatchTime;
    }

    public String getMdpOperationtype() {
        return mdpOperationtype;
    }

    public void setMdpOperationtype(String mdpOperationtype) {
        this.mdpOperationtype = mdpOperationtype;
    }

    public String getMdpResult() {
        return mdpResult;
    }

    public void setMdpResult(String mdpResult) {
        this.mdpResult = mdpResult;
    }

}
