package eccrm.base.role.vo;

import eccrm.base.tenement.vo.CrmBaseVo;

import java.util.Date;

/**
 * Generated by miles on 2014-07-21.
 */

public class RoleUserVo extends CrmBaseVo {

    private String userId;
    private String username;
    private String roleId;
    private String roleName;
    private String roleCode;
    private String roleDescription;
    private Date roleEndDate;
    private String roleState;
    private String rolePinYin;

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getRoleId() {
        return roleId;
    }

    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    public String getRoleCode() {
        return roleCode;
    }

    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode;
    }

    public String getRolePinYin() {
        return rolePinYin;
    }

    public void setRolePinYin(String rolePinYin) {
        this.rolePinYin = rolePinYin;
    }

    public String getRoleDescription() {
        return roleDescription;
    }

    public void setRoleDescription(String roleDescription) {
        this.roleDescription = roleDescription;
    }

    public Date getRoleEndDate() {
        return roleEndDate;
    }

    public void setRoleEndDate(Date roleEndDate) {
        this.roleEndDate = roleEndDate;
    }

    public String getRoleState() {
        return roleState;
    }

    public void setRoleState(String roleState) {
        this.roleState = roleState;
    }
}
