package eccrm.base.employee.dao;

import eccrm.base.employee.bo.BlankListBo;
import eccrm.base.employee.domain.BlankList;
import eccrm.base.employee.domain.Employee;
import eccrm.base.org.domain.Organization;

import java.util.List;

/**
 * Generated by liuxq on 2014-10-22.
 */

public interface BlankListDao {

    String save(BlankList blankList);

    void update(BlankList blankList);

    List<BlankList> query(BlankListBo bo);

    long getTotal(BlankListBo bo);

    BlankList findById(String id);

    int deleteById(String id);

    /**
     * 根据条件查询在白名单中的员工列表(如果有分页信息，则会按照分页查询）
     *
     * @param bo 高级查询对象
     * @return 员工信息
     */
    List<Employee> queryEmployees(BlankListBo bo);

    /**
     * 查询符合条件的白名单员工的数量（一般用于分页查询中）
     *
     * @param bo 高级查询对象
     * @return 白名单员工总数
     */
    long getEmployeesCount(BlankListBo bo);

    /**
     * 查询员工在白名单岗位中对应的组织机构信息
     *
     * @param empId 员工id
     */
    List<Organization> queryBlankListEmpDept(String empId);
}
