package eccrm.base.employee.dao;

import eccrm.base.employee.bo.EmployeeOrgRelBo;
import eccrm.base.employee.domain.EmployeeOrgRel;

import java.util.List;

/**
* Generated by yanhx on 2014-10-13.
*/

public interface EmployeeOrgRelDao {

    String save(EmployeeOrgRel employeeOrgRelOf);

    void update(EmployeeOrgRel employeeOrgRelOf);

    List<EmployeeOrgRel> query(EmployeeOrgRelBo bo);

    long getTotal(EmployeeOrgRelBo bo);

    EmployeeOrgRel findById(String id);

    int deleteById(String id);

    List<EmployeeOrgRel> queryByOrgId(String id);
}
