package eccrm.base.employee.dao;

import eccrm.base.employee.bo.EmployeePositionBo;
import eccrm.base.employee.domain.EmployeePosition;

import java.util.List;

/**
* Generated by yanhx on 2014-10-13.
*/

public interface EmployeePositionDao {

    String save(EmployeePosition employeePosition);

    void update(EmployeePosition employeePosition);

    List<EmployeePosition> query(EmployeePositionBo bo);

    long getTotal(EmployeePositionBo bo);

    EmployeePosition findById(String id);

    int deleteById(String id);
}
