package eccrm.base.position.domain;


import com.ycrl.base.common.CommonDomain;

import java.util.List;

/**
 * Generated by chenl on 2014-10-20.
 */

public class PositionParam extends CommonDomain{
    private String busiType;
    private String orgType;
    private Position position;
    private List<Position> positions;

    public List<Position> getPositions() {
        return positions;
    }

    public void setPositions(List<Position> positions) {
        this.positions = positions;
    }

    public String getBusiType() {
        return busiType;
    }

    public void setBusiType(String busiType) {
        this.busiType = busiType;
    }

    public String getOrgType() {
        return orgType;
    }

    public void setOrgType(String orgType) {
        this.orgType = orgType;
    }

    public Position getPosition() {
        return position;
    }

    public void setPosition(Position position) {
        this.position = position;
    }

}
