package eccrm.base.position.domain;

import com.ycrl.base.common.CommonDomain;
import eccrm.base.org.domain.Organization;

import java.util.Date;

/**
 * Generated by chenl on 2014-10-11.
 */


public class Position extends CommonDomain {
    private String pinyin;//全拼
    private String shortName;//简称
    private String jianPin;//说明
    private String name;//角色名称
    private String code;//角色编号
    private Date startDate;//启用时间
    private Date endDate;//失效时间
    private Classify classify;//计划人员

    private String positionType;// 岗位类型：对应Classify的id

    private String roleType;//岗位类型
    private String busiTypeNo;//所属系统
    private Organization organization;//机构
    private Integer empCount;//计划人员
    private Integer minEmpCount;//最少人员
    private Boolean isAlert;//是否预警

    public String getPinyin() {
        return pinyin;
    }

    public void setPinyin(String pinyin) {
        this.pinyin = pinyin;
    }

    public String getShortName() {
        return shortName;
    }

    public void setShortName(String shortName) {
        this.shortName = shortName;
    }

    public String getJianPin() {
        return jianPin;
    }

    public void setJianPin(String jianPin) {
        this.jianPin = jianPin;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public Date getStartDate() {
        return startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getEndDate() {
        return endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public Classify getClassify() {
        return classify;
    }

    public void setClassify(Classify classify) {
        this.classify = classify;
    }

    public String getRoleType() {
        return roleType;
    }

    public void setRoleType(String roleType) {
        this.roleType = roleType;
    }

    public String getBusiTypeNo() {
        return busiTypeNo;
    }

    public void setBusiTypeNo(String busiTypeNo) {
        this.busiTypeNo = busiTypeNo;
    }

    public Organization getOrganization() {
        return organization;
    }

    public void setOrganization(Organization organization) {
        this.organization = organization;
    }

    public Integer getEmpCount() {
        return empCount;
    }

    public void setEmpCount(Integer empCount) {
        this.empCount = empCount;
    }

    public Integer getMinEmpCount() {
        return minEmpCount;
    }

    public void setMinEmpCount(Integer minEmpCount) {
        this.minEmpCount = minEmpCount;
    }

    public Boolean getIsAlert() {
        return isAlert;
    }

    public void setIsAlert(Boolean isAlert) {
        this.isAlert = isAlert;
    }

    public String getPositionType() {
        return positionType;
    }

    public void setPositionType(String positionType) {
        this.positionType = positionType;
    }
}
