package eccrm.base.position.domain;

import com.ycrl.base.common.CommonDomain;
import eccrm.base.employee.domain.Employee;
import eccrm.base.org.domain.Organization;

/**
 * Generated by chenl on 2014-10-18.
 */

public class PositionEmp extends CommonDomain {


    private Employee employee;
    private String empId;
    private Position position;
    private String positionId;
    private Organization org;
    private String orgId;

    public String getOrgId() {
        return orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }



    public String getEmpId() {
        return empId;
    }

    public void setEmpId(String empId) {
        this.empId = empId;
    }

    public String getPositionId() {
        return positionId;
    }

    public void setPositionId(String positionId) {
        this.positionId = positionId;
    }

    public Employee getEmployee() {
        return employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    public Position getPosition() {
        return position;
    }

    public void setPosition(Position position) {
        this.position = position;
    }

    public Organization getOrg() {
        return org;
    }

    public void setOrg(Organization org) {
        this.org = org;
    }
}
