package eccrm.base.org.dao;


import eccrm.base.org.bo.OrgPositionBo;
import eccrm.base.org.domain.OrgPosition;
import eccrm.base.position.domain.Position;

import java.util.List;

/**
 * Generated by yanhx on 2014-10-13.
 */

public interface OrgPositionDao {

    String save(OrgPosition orgPosition);

    void update(OrgPosition orgPosition);

    List<OrgPosition> query(OrgPositionBo bo);

    Long getTotal(OrgPositionBo bo);

    OrgPosition findById(String id);

    int deleteById(String id);

    int deleteByRoleId(OrgPositionBo bo);

    List<OrgPosition> querys(OrgPositionBo orgPositionBo);

    boolean isExit(String orgId, String positionId);


    /**
     * 查询所有具有岗位的组织机构的id集合
     *
     * @return 组织机构id集合
     */
    List<String> whoHasPosition();


    /**
     * 查询一个组织机构下的所有的岗位信息
     * <p>注意：只返回岗位的基本信息</p>
     * <p>如果设置了Pager属性，则会进行分页查询</p>
     *
     * @param orgId 组织机构id
     */
    List<Position> queryByOrgId(String orgId);

    OrgPosition queryByRoleId(String code);
}
