package eccrm.base.org.domain;


import com.ycrl.base.common.CommonDomain;

/**
 * 机构岗位
* Generated by yanhx on 2014-10-13.
*/

public class OrgPosition extends CommonDomain {

    private String orgId;
    private String roleId;

    public String getOrgId() {
        return orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    public String getRoleId() {
        return roleId;
    }

    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }


    public OrgPosition() {
    }
}
