package eccrm.base.position.dao;


import com.ycrl.utils.tree.PathTreeDao;
import eccrm.base.position.bo.ClassifyBo;
import eccrm.base.position.domain.Classify;

import java.util.List;
import java.util.Set;

/**
 * Generated by chenl on 2014-10-13.
 */

public interface ClassifyDao extends PathTreeDao<Classify, String> {

    String save(Classify classify);

    void update(Classify classify);

    List<Classify> query(ClassifyBo bo);

    long getTotal(ClassifyBo bo);

    Classify findById(String id);

    int deleteById(String id);

    /**
     * 查询指定id集合中，是上级的id的集合
     *
     * @param ids id集合
     */
    List<String> isParent(Set<String> ids);

    /**
     * 查询指定ID集合中，包含岗位的分类的ID集合
     *
     * @param ids 分类ID集合
     */
    List<String> hasPosition(Set<String> ids);
}
