package eccrm.base.position.dao;


import eccrm.base.log.OperateType;
import eccrm.base.log.annotations.LogInfo;
import eccrm.base.position.bo.PositionBo;
import eccrm.base.position.domain.Position;

import java.util.List;

/**
 * Generated by chenl on 2014-10-11.
 */

public interface PositionDao {

    @LogInfo(type = OperateType.ADD, describe = "岗位-新增")
    String save(Position position);

    @LogInfo(type = OperateType.MODIFY, describe = "岗位-修改")
    void update(Position position);

    List<Position> query(PositionBo bo);

    long getTotal(PositionBo bo);

    Position findById(String id);

    @LogInfo(type = OperateType.DELETE, describe = "岗位-删除")
    int deleteById(String id);

    List<Position> findByCode(String code);

    /**
     * 判断指定名称是否存在
     * 存在：true，不存在：false
     *
     * @param id   可选，如果不为空，表示查询跳过id为当前值的这条记录
     * @param name 名称
     */
    boolean hasName(String id, String name);

    /**
     * 判断指定编号是否存在
     * 存在：true，不存在：false
     *
     * @param id   可选，如果不为空，表示查询跳过id为当前值的这条记录
     * @param code 编号
     */
    boolean hasCode(String id, String code);

    Boolean findByName(String name);

    /**
     * 查询岗位名称对应的ID列表
     *
     * @param positionNames 岗位名称数组
     * @return 岗位ID集合
     */
    List<String> findIdByName(String[] positionNames);

    /**
     * 根据岗位名称查找对应的岗位信息（精确匹配）
     *
     * @param positionName 岗位名称
     */
    List<Position> findByPositionName(String positionName);

    /**
     * 根据编号查询岗位
     * 如果存在多条，则会抛出异常
     *
     * @return 岗位
     */
    Position queryByCode(String code);

    /**
     * 判断指定分类下是否具有岗位
     *
     * @param positionCategoryId 岗位分类ID
     * @return true：有岗位、false没有岗位
     */
    boolean hasPosition(String positionCategoryId);
}
