package eccrm.base.position.dao;


import eccrm.base.position.bo.PositionParamBo;
import eccrm.base.position.domain.PositionParam;

import java.util.List;

/**
 * Generated by chenl on 2014-10-20.
 */

public interface PositionParamDao {

    String save(PositionParam positionParam);

    void update(PositionParam positionParam);

    List<PositionParam> query(PositionParamBo bo);

    long getTotal(PositionParamBo bo);

    PositionParam findById(String id);

    int deleteById(String id);

    List<PositionParam> findByPosition(String[] busiType);
    boolean isExit(String busiType, String orgType, String positionId);
}
