package ${packagePath}.bo;

import ${packagePath}.domain.${entity};

/**
 * Generated by <#if author??>${author}</#if> on <#if current??>${current}</#if>.
 */
public class ${entity}Bo extends ${entity} {

}
