package ${packagePath}.dao;

import com.ycrl.core.pager.PageVo;
import ${packagePath}.bo.${entity}Bo;
import ${packagePath}.domain.${entity};
import ${packagePath}.vo.${entity}Vo;
import java.util.List;

/**
 * Generated by <#if author??>${author}</#if> on <#if current??>${current}</#if>.
 */
public interface ${entity}Dao {

    String save(${entity} ${lowerEntity});

    void update(${entity} ${lowerEntity});

    List<${entity}> query(${entity}Bo bo);

    long getTotal(${entity}Bo bo);

    ${entity} findById(String id);

    void deleteById(String id);
}
