package ${packagePath}.domain;

import eccrm.base.tenement.domain.CrmBaseDomain;

/**
 * Generated by <#if author??>${author}</#if> on <#if current??>${current}</#if>.
 */
public class ${entity} extends CrmBaseDomain {

    // 只写业务属性即可

}
