package ${packagePath}.dao.impl;

import ${packagePath}.bo.${entity}Bo;
import ${packagePath}.dao.${entity}Dao;
import ${packagePath}.vo.${entity}Vo;
import ${packagePath}.domain.${entity};
import com.ycrl.core.pager.PageVo;
import eccrm.utils.gson.GsonUtils;
import static junit.framework.Assert.*;
import org.apache.log4j.Logger;
import org.hibernate.SessionFactory;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import eccrm.${module}.AbstractTestWrapper;

import javax.annotation.Resource;
import java.util.List;

/**
* Generated by <#if author??>${author}</#if> on <#if current??>${current}</#if>.
*/

public class ${entity}DaoImplTest extends AbstractTestWrapper{

    @Resource
    private ${entity}Dao dao;

    private Logger logger = Logger.getLogger(${entity}DaoImplTest.class);

    @Before
    public void setUp() throws Exception {
        logger.info(" test ${packagePath}.dao.impl.${entity}DaoImpl ......");
    }

    @Test
    public void testSave() {
        logger.info(" save ......");
    }

    @Test
    public void testFindById() {
        logger.info("test findById() ... ");
    }

    @Test
    public void testQuery() throws Exception {
        logger.info("test query() .. ");
    }

    @Test
    public void testUpdate() throws Exception {
        logger.info("test update() ... ");
    }

    @Test
    public void testDeleteById() {
    }

}
