package ${packagePath}.service;

import com.ycrl.core.pager.PageVo;
import ${packagePath}.bo.${entity}Bo;
import ${packagePath}.domain.${entity};
import ${packagePath}.vo.${entity}Vo;

/**
 * Generated by <#if author??>${author}</#if> <#if current??>on ${current}</#if>.
 */
public interface ${entity}Service {

    /**
     * 保存实体类，并返回保存后的id
     */
    String save(${entity} ${lowerEntity});

    void update(${entity} ${lowerEntity});

    /**
     * <p>高级查询，会根据当前对象中的属性进行模糊匹配查询</p>
     * <p>如果当前对象为空，则查询全部</p>
     * <p>该方法接收分页参数、排序参数（在上下文中设置）</p>
     * <p>返回分页对象</p>
     */
    PageVo query(${entity}Bo bo);

    ${entity}Vo findById(String id);

    void deleteByIds(String... ids);

}
