package ${packagePath}.service.impl;

import com.ycrl.core.pager.PageVo;
import com.ycrl.core.beans.BeanWrapBuilder;
import ${packagePath}.bo.${entity}Bo;
import ${packagePath}.domain.${entity};
import ${packagePath}.vo.${entity}Vo;
import ${packagePath}.dao.${entity}Dao;
import ${packagePath}.service.${entity}Service;
import org.springframework.stereotype.Service;
import javax.annotation.Resource;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Generated by <#if author??>${author}</#if> on <#if current??>${current}</#if>.
 */
@Service("${lowerEntity}Service")
public class ${entity}ServiceImpl implements ${entity}Service {
    @Resource
    private ${entity}Dao ${lowerEntity}Dao;

    @Override
    public String save(${entity} ${lowerEntity}) {
        String id = ${lowerEntity}Dao.save(${lowerEntity});
        return id;
    }

    @Override
    public void update(${entity} ${lowerEntity}) {
        ${lowerEntity}Dao.update(${lowerEntity});
    }

    @Override
    public PageVo query(${entity}Bo bo) {
        PageVo vo = new PageVo();
        Long total = ${lowerEntity}Dao.getTotal(bo);
        vo.setTotal(total);
        if (total == 0) return vo;
        List<${entity}> ${lowerEntity}s = ${lowerEntity}Dao.query(bo);
        List<${entity}Vo> vos = BeanWrapBuilder.newInstance()
            .wrapList(${lowerEntity}s, ${entity}Vo.class);
        vo.setData(vos);
        return vo;
    }

    @Override
    public ${entity}Vo findById(String id) {
        ${entity} ${lowerEntity} = ${lowerEntity}Dao.findById(id);
        ${entity}Vo vo = BeanWrapBuilder.newInstance()
            .wrap(${lowerEntity}, ${entity}Vo.class);
        return vo;
    }


    @Override
    public void deleteByIds(String... ids) {
        if (ids == null || ids.length == 0) return;
        for (String id : ids) {
            ${lowerEntity}Dao.deleteById(id);
        }
    }

}
