package ${packagePath}.vo;

import eccrm.base.tenement.vo.CrmBaseVo;

/**
 * Generated by <#if author??>${author}</#if> on <#if current??>${current}</#if>.
 */
public class ${entity}Vo extends CrmBaseVo {


}
