package eccrm.base.employee.service;


import com.ycrl.core.pager.PageVo;
import eccrm.base.employee.bo.BlankListBo;
import eccrm.base.employee.domain.BlankList;
import eccrm.base.employee.vo.BlankListVo;
import eccrm.base.employee.vo.EmployeeVo;

import java.util.List;

/**
 * Generated by liuxq on 2014-10-22.
 */

public interface BlankListService {

    String save(BlankList blankList);

    void update(BlankList blankList);

    PageVo query(BlankListBo bo);

    BlankListVo findById(String id);

    void deleteByIds(String... ids);

    /**
     * 根据号码查询白名单，存在返回true 不存在翻false
     * address结构：区号-号码-座机号 最终组合成address
     *
     * @param address 号码
     * @return
     */
    Boolean isBlankList(String address);

    List<EmployeeVo> queryEmployees(BlankListBo bo);

    /**
     * 根据条件分页查询白名单中的员工
     *
     * @param bo 高级查询对象
     * @return 分页对象
     */
    PageVo pageQueryEmployees(BlankListBo bo);
}
