package eccrm.base.employee.service;

/**
* Generated by liuxq on 2014-10-21.
 * 工单所有业务参数code
*/

public interface BlankListType {
    /**
     * 业务事项
     */
    static String BUSINESS_MATTER = "BP_YWSX";

    /**
     * 状态
     */
    static String STATUS = "SP_COMMON_STATE";


}
