package eccrm.base.employee.service;


import com.ycrl.core.beans.BeanWrapper;
import com.ycrl.core.pager.PageVo;
import eccrm.base.employee.bo.ContactMethodBo;
import eccrm.base.employee.domain.ContactMethod;
import eccrm.base.employee.vo.ContactMethodVo;

/**
 * Generated by chenl on 2014-10-22.
 */

public interface ContactMethodService extends BeanWrapper<ContactMethod, ContactMethodVo> {
    public static final String BP_STAFF = "BP_STAFF";//员工
    public static final String BP_CLIENT = "BP_CLIENT";//客户
    String save(ContactMethod contactMethod);

    void update(ContactMethod contactMethod);

    PageVo query(ContactMethodBo bo);

    ContactMethodVo findById(String id);

    void deleteByIds(String... ids);
    /**
     * 如果号码不显示 手机号：136****8888 电话：010-888*****-020
     * @param preAddr 区号
     * @param address 电话号码
     * @param aftAddr 分机号
     * @return
     */
    String phoneShow(String preAddr, String address, String aftAddr);
}
