package eccrm.base.employee.service;

import com.ycrl.core.beans.BeanWrapper;
import com.ycrl.core.pager.PageVo;
import eccrm.base.employee.bo.EmployeeBo;
import eccrm.base.employee.domain.Employee;
import eccrm.base.employee.vo.EmployeeVo;

import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import java.util.List;

/**
 * Generated by yanhx on 2014-10-13.
 */
@WebService
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface EmployeeService extends BeanWrapper<Employee, EmployeeVo> {

    String save(Employee employee);

    void update(Employee employee);

    PageVo query(EmployeeBo bo);

    List<EmployeeVo> querys(EmployeeBo bo);

    EmployeeVo findById(String id);

    EmployeeVo findRTX(String extensionNumber);

    EmployeeVo findByCode(String id);

    void deleteByIds(String... ids);

    List<Employee> queryByOrgId(String id);

    List<EmployeeVo> queryByRuleId(String id, String orgId);

    EmployeeVo wrap(Employee employee);

    /**
     * 根据来电号码查询是否白名单
     *
     * @param mobile 电话
     * @return
     */
    EmployeeVo queryByMobile(String mobile);

    /**
     * 判断指定rtxId的员工是否存在
     *
     * @param rtxId
     * @return true存在，false不存在
     */
    boolean isExists(String rtxId);

    /**
     * 根据员工ID查询员工名称
     *
     * @param employeeId 员工id
     * @return 员工名称
     */
    String findNameById(String employeeId);

    /**
     * 根据员工ID查询员工
     *
     * @return 员工
     */
    Employee findById2(String employID);

    /**
     * 只查询员工状态为（正式、调动中、实习）的数据
     */
    PageVo queryValid(EmployeeBo bo);

    /**
     * 带权限的高级查询
     *
     * @param bo 高级查询对象
     */
    PageVo permissionPageQuery(EmployeeBo bo);
}
