package eccrm.base.employee.service;

import com.ycrl.core.beans.BeanWrapper;
import com.ycrl.core.pager.PageVo;
import eccrm.base.employee.bo.EmployeeOrgRelBo;
import eccrm.base.employee.domain.Employee;
import eccrm.base.employee.domain.EmployeeOrgRel;
import eccrm.base.employee.vo.EmployeeOrgRelVo;

import java.util.List;

/**
* Generated by yanhx on 2014-10-13.
*/

public interface EmployeeOrgRelService extends BeanWrapper<EmployeeOrgRel, EmployeeOrgRelVo>{

    String save(EmployeeOrgRel employeeOrgRel);

    void update(EmployeeOrgRel employeeOrgRel);

    PageVo query(EmployeeOrgRelBo bo);

    EmployeeOrgRelVo findById(String id);

    void deleteByIds(String... ids);
    List<Employee> findByOrgId(String id);
}
