package eccrm.base.employee.service;

import eccrm.base.employee.domain.Employee;

import java.util.List;

/**
* Generated by yanhx on 2014-10-13.
*/

public interface EmployeeOutsideService {

    List<Employee> queryByOrgId(String id);
}
