package eccrm.base.contact.dao;


import eccrm.base.contact.bo.ContactBo;
import eccrm.base.contact.domain.Contact;

import java.util.List;

/**
 * Generated by chenl on 2014-09-22.
 */

public interface ContactDao {

    String save(Contact contact);

    void update(Contact contact);

    List<Contact> query(ContactBo bo);

    long getTotal(ContactBo bo);

    /**
     * 返回对象
     * @param sheetNo  工单编号
     * @param nodeName 节点名称
     * @return
     */
    List<Contact> findBySheetNo(String sheetNo, String nodeName);

    Contact findById(String id);

    /**
     * 根据录音编号查询对应的联络记录
     * @param recordId 录音编号
     */
    Contact findByRecordId(String recordId);

    int deleteById(String id);
}
