package eccrm.base.employee.dao.impl;

import eccrm.base.employee.bo.ContactMethodBo;
import eccrm.base.employee.dao.ContactMethodDao;
import eccrm.base.employee.domain.ContactMethod;
import com.ycrl.core.HibernateDaoHelper;
import org.hibernate.Criteria;
import org.hibernate.criterion.Example;
import org.hibernate.criterion.MatchMode;
import org.springframework.stereotype.Repository;

import java.util.List;


/**
 * Generated by chenl on 2014-10-22.
 */

@Repository("contactMethodDao")
public class ContactMethodDaoImpl extends HibernateDaoHelper implements ContactMethodDao {

    @Override
    public String save(ContactMethod contactMethod) {
        return (String) getSession().save(contactMethod);
    }

    @Override
    public void update(ContactMethod contactMethod) {
        getSession().update(contactMethod);
    }

    @Override
    public List<ContactMethod> query(ContactMethodBo bo) {
        Criteria criteria = getDefaultCriteria(bo);
        return criteria.list();
    }

    @Override
    public long getTotal(ContactMethodBo bo) {
        Criteria criteria = createRowCountsCriteria(ContactMethod.class);
        initCriteria(criteria, bo);
        return (Long) criteria.uniqueResult();
    }


    @Override
    public int deleteById(String id) {
        return getSession().createQuery("delete from ContactMethod where id=?")
                .setParameter(0, id)
                .executeUpdate();
    }

    @Override
    public ContactMethod findById(String id) {
        return (ContactMethod) getSession().get(ContactMethod.class, id);
    }

    /**
     * 获得默认的org.hibernate.Criteria对象,并根据bo进行初始化（如果bo为null，则会新建一个空对象）
     * 为了防止新的对象中有数据，建议实体/BO均采用封装类型
     */
    private Criteria getDefaultCriteria(ContactMethodBo bo) {
        Criteria criteria = createCriteria(ContactMethod.class);
        initCriteria(criteria, bo);
        return criteria;
    }

    /**
     * 根据BO初始化org.hibernate.Criteria对象
     * 如果org.hibernate.Criteria为null，则抛出异常
     * 如果BO为null，则新建一个空的对象
     */
    private void initCriteria(Criteria criteria, ContactMethodBo bo) {
        if (criteria == null) {
            throw new IllegalArgumentException("criteria must not be null!");
        }
        if (bo == null) bo = new ContactMethodBo();
        criteria.add(Example.create(bo).enableLike(MatchMode.ANYWHERE).ignoreCase());
    }

}