package eccrm.base.employee.dao.impl;

import eccrm.base.employee.bo.EmployeePositionBo;
import eccrm.base.employee.dao.EmployeePositionDao;
import eccrm.base.employee.domain.EmployeePosition;
import com.ycrl.core.HibernateDaoHelper;
import org.hibernate.Criteria;
import org.hibernate.criterion.Example;
import org.hibernate.criterion.MatchMode;
import org.springframework.stereotype.Repository;

import java.util.List;


/**
* Generated by yanhx on 2014-10-13.
*/

@Repository("employeePositionDao")
public class EmployeePositionDaoImpl extends HibernateDaoHelper implements EmployeePositionDao {

    @Override
    public String save(EmployeePosition employeePosition) {
        return (String)getSession().save(employeePosition);
    }

    @Override
    public void update(EmployeePosition employeePosition) {
        getSession().update(employeePosition);
    }

    @Override
    public List<EmployeePosition> query(EmployeePositionBo bo) {
        Criteria criteria = getDefaultCriteria(bo);
        return criteria.list();
    }

    @Override
    public long getTotal(EmployeePositionBo bo) {
        Criteria criteria = createRowCountsCriteria(EmployeePosition.class);
        initCriteria(criteria, bo);
        return (Long) criteria.uniqueResult();
    }


    @Override
    public int deleteById(String id) {
        return getSession().createQuery("delete from EmployeePosition where id=?")
        .setParameter(0, id)
        .executeUpdate();
    }

    @Override
    public EmployeePosition findById(String id) {
        return (EmployeePosition) getSession().get(EmployeePosition.class, id);
    }

    /**
    * 获得默认的org.hibernate.Criteria对象,并根据bo进行初始化（如果bo为null，则会新建一个空对象）
    * 为了防止新的对象中有数据，建议实体/BO均采用封装类型
    */
    private Criteria getDefaultCriteria(EmployeePositionBo bo){
        Criteria criteria = createCriteria(EmployeePosition.class);
        initCriteria(criteria, bo);
        return criteria;
    }

    /**
    *  根据BO初始化org.hibernate.Criteria对象
    *  如果org.hibernate.Criteria为null，则抛出异常
    *  如果BO为null，则新建一个空的对象
    */
    private void initCriteria(Criteria criteria, EmployeePositionBo bo) {
        if (criteria == null) {
            throw new IllegalArgumentException("criteria must not be null!");
        }
        if (bo == null) bo = new EmployeePositionBo();
        criteria.add(Example.create(bo).enableLike(MatchMode.ANYWHERE).ignoreCase());
    }

}