package eccrm.base.employee.dao.impl;

import eccrm.base.employee.bo.EmployeeOrgRelBo;
import eccrm.base.employee.dao.EmployeeOrgRelDao;
import eccrm.base.employee.domain.EmployeeOrgRel;
import com.ycrl.core.HibernateDaoHelper;
import com.ycrl.core.exception.Argument;
import org.hibernate.Criteria;
import org.hibernate.criterion.Example;
import org.hibernate.criterion.MatchMode;
import org.hibernate.criterion.Restrictions;
import org.springframework.stereotype.Repository;

import java.util.List;


/**
* Generated by yanhx on 2014-10-13.
*/

@Repository("employeeOrgRelDao")
public class EmployeeOrgRelDaoImpl extends HibernateDaoHelper implements EmployeeOrgRelDao {

    @Override
    public String save(EmployeeOrgRel employeeOrgRel) {
        return (String)getSession().save(employeeOrgRel);
    }

    @Override
    public void update(EmployeeOrgRel employeeOrgRel) {
        getSession().update(employeeOrgRel);
    }

    @Override
    public List<EmployeeOrgRel> query(EmployeeOrgRelBo bo) {
        Criteria criteria = getDefaultCriteria(bo);
        return criteria.list();
    }
    @Override
    public List<EmployeeOrgRel> queryByOrgId(String id) {

        Argument.isEmpty(id, "查询岗位ID不能为空");
        Criteria criteria = createCriteria(EmployeeOrgRel.class);
        criteria.add(Restrictions.eq("organization.id", id));
        return criteria.list();
    }
    @Override
    public long getTotal(EmployeeOrgRelBo bo) {
        Criteria criteria = createRowCountsCriteria(EmployeeOrgRel.class);
        initCriteria(criteria, bo);
        return (Long) criteria.uniqueResult();
    }


    @Override
    public int deleteById(String id) {
        return getSession().createQuery("delete from EmployeeOrgRel where id=?")
        .setParameter(0, id)
        .executeUpdate();
    }

    @Override
    public EmployeeOrgRel findById(String id) {
        return (EmployeeOrgRel) getSession().get(EmployeeOrgRel.class, id);
    }

    /**
    * 获得默认的org.hibernate.Criteria对象,并根据bo进行初始化（如果bo为null，则会新建一个空对象）
    * 为了防止新的对象中有数据，建议实体/BO均采用封装类型
    */
    private Criteria getDefaultCriteria(EmployeeOrgRelBo bo){
        Criteria criteria = createCriteria(EmployeeOrgRel.class);
        initCriteria(criteria, bo);
        return criteria;
    }

    /**
    *  根据BO初始化org.hibernate.Criteria对象
    *  如果org.hibernate.Criteria为null，则抛出异常
    *  如果BO为null，则新建一个空的对象
    */
    private void initCriteria(Criteria criteria, EmployeeOrgRelBo bo) {
        if (criteria == null) {
            throw new IllegalArgumentException("criteria must not be null!");
        }
        if (bo == null) bo = new EmployeeOrgRelBo();
        criteria.add(Example.create(bo).enableLike(MatchMode.ANYWHERE).ignoreCase());
    }

}