package eccrm.base.position.vo;


import com.ycrl.base.common.CommonVo;

/**
 * Generated by chenl on 2014-10-20.
 */

public class PositionParamVo extends CommonVo {
    private String busiType;
    private String busiTypeName;
    private String orgType;
    private String orgTypeName;
    private String positionId;
    private String positionName;
    private String statusName;
    private PositionVo positionVo;

    public PositionVo getPositionVo() {
        return positionVo;
    }

    public void setPositionVo(PositionVo positionVo) {
        this.positionVo = positionVo;
    }

    public String getStatusName() {
        return statusName;
    }

    public void setStatusName(String statusName) {
        this.statusName = statusName;
    }

    public String getBusiTypeName() {

        return busiTypeName;
    }

    public void setBusiTypeName(String busiTypeName) {
        this.busiTypeName = busiTypeName;
    }

    public String getBusiType() {
        return busiType;
    }

    public void setBusiType(String busiType) {
        this.busiType = busiType;
    }

    public String getOrgType() {
        return orgType;
    }

    public void setOrgType(String orgType) {
        this.orgType = orgType;
    }

    public String getOrgTypeName() {
        return orgTypeName;
    }

    public void setOrgTypeName(String orgTypeName) {
        this.orgTypeName = orgTypeName;
    }

    public String getPositionId() {
        return positionId;
    }

    public void setPositionId(String positionId) {
        this.positionId = positionId;
    }

    public String getPositionName() {
        return positionName;
    }

    public void setPositionName(String positionName) {
        this.positionName = positionName;
    }



}
