package eccrm.base.role.dao;

import eccrm.base.role.domain.RoleUser;

import java.util.List;

/**
 * Generated by miles on 2014-07-21.
 */

public interface RoleUserDao {

    String save(RoleUser roleUser);

    void deleteByUserId(String userId);

    List<RoleUser> queryByUserId(String userId);

    List<String> queryRoleIds(String userId);

    void deleteByIds(String[] ids);
}
