package eccrm.base.role.dao;

import eccrm.base.role.domain.RoleGroup;

import java.util.List;

/**
 * Generated by miles on 2014-07-21.
 */

public interface RoleGroupDao {

    String save(RoleGroup roleGroup);

    void deleteByGroupId(String groupId);

    List<RoleGroup> queryByGroupId(String groupId);

    List<String> queryIdsByGroupId(String groupId);

    List<RoleGroup> queryByGroupIds(String[] groupIds);

    /**
     * 获得指定用户组下的最后一个序列号
     *
     * @param groupId 用户组
     */
    int lastSequenceNo(String groupId);

    void deleteByIds(String[] ids);
}
