package eccrm.base.role.dao;

import eccrm.base.menu.domain.Menu;
import eccrm.base.role.domain.RoleResource;

import java.util.List;

/**
 * Generated by miles on 2014-07-21.
 */

public interface RoleResourceDao {

    void save(RoleResource roleResource);

    /**
     * 根据角色id查询对应的资源列表
     *
     * @param roleId 角色id
     * @return 资源列表
     */
    List<Menu> queryByRoleId(String roleId);

    /**
     * 根据用户id查询所有的资源
     *
     * @param userId 用户id
     * @return 资源列表
     */
    List<Menu> queryByUserId(String userId);

    /**
     * 根据角色id删除对应的关联关系
     *
     * @param roleId 角色id
     */
    void deleteByRoleId(String roleId);

    /**
     * 根据id删除
     *
     * @param id id
     */
    void deleteById(String id);

    /**
     * 查询所有不允许被指定用户访问的资源
     *
     * @param userId 用户id
     * @return 资源列表
     */
    List<Menu> defendAccessResources(String userId);
}
