package eccrm.base.position.service.impl;


import eccrm.base.position.bo.PositionParamBo;
import eccrm.base.position.dao.PositionParamDao;
import eccrm.base.position.domain.Position;
import eccrm.base.position.domain.PositionParam;
import eccrm.base.position.service.PositionParamService;
import eccrm.base.position.service.PositionService;
import eccrm.base.position.vo.PositionParamVo;
import com.ycrl.core.beans.BeanWrapBuilder;
import com.ycrl.core.beans.BeanWrapCallback;
import com.ycrl.core.pager.PageVo;
import eccrm.base.parameter.service.ParameterContainer;
import org.springframework.beans.BeanUtils;
import org.springframework.stereotype.Service;

import javax.annotation.Resource;
import java.util.ArrayList;
import java.util.List;

/**
 * Generated by chenl on 2014-10-20.
 */

@Service("positionParamService")
public class PositionParamServiceImpl implements PositionParamService, BeanWrapCallback<PositionParam, PositionParamVo> {
    public static final String SYS_BUSI_TYPE = "BP_YETAI";
    public static final String SYS_ORGAN = "BP_ORGAN";
    @Resource
    private PositionParamDao positionParamDao;
    @Resource
    private PositionService positionService;

    @Override
    public String save(PositionParam positionParam) {
        if(positionParam ==null) return null;
        String id =null;
     String  busiType = positionParam.getBusiType();
     String  orgType  = positionParam.getOrgType();
        List<Position> positions = positionParam.getPositions();
        if( positions !=null && positions.size()>0){
            for(Position position:positions){
                String positionId = position.getId();
                if(positionId != null){
                    if(positionParamDao.isExit(busiType,orgType,positionId)){
                        PositionParam positionParam1 = new PositionParam();
                        BeanUtils.copyProperties(positionParam, positionParam1);
                        positionParam1.setPosition(position);
                        positionParamDao.save(positionParam1);
                    }
                }
            }
        }
        return id;
    }

    @Override
    public void update(PositionParam positionParam) {
        positionParamDao.update(positionParam);
    }

    @Override
    public PageVo query(PositionParamBo bo) {
        PageVo vo = new PageVo();
        Long total = positionParamDao.getTotal(bo);
        vo.setTotal(total);
        if (total == 0) return vo;
        List<PositionParam> positionParams = positionParamDao.query(bo);
        vo.setData(BeanWrapBuilder.newInstance()
                .setCallback(this)
                .wrapList(positionParams, PositionParamVo.class));
        return vo;
    }

    @Override
    public PositionParamVo findById(String id) {
        return wrap(positionParamDao.findById(id));
    }


    @Override
    public void deleteByIds(String... ids) {
        if (ids == null || ids.length == 0) return;
        for (String id : ids) {
            positionParamDao.deleteById(id);
        }
    }

    @Override
    public List<Position> findByPosition(String... busiType) {
        if (busiType == null || busiType.length == 0) return null;
        List<PositionParam> positionParams = positionParamDao.findByPosition(busiType);
        List<Position> positionList = new ArrayList<Position>();

        if (positionParams != null && positionParams.size() > 0) {
            for (PositionParam positionParam : positionParams) {
                Position position = positionParam.getPosition();
                if (position != null && position.getId() != null) {
                    positionList.add(position);
                }
            }

        }
        return positionList;
    }


    public PositionParamVo wrap(PositionParam positionParam) {
        if (positionParam == null) return null;
        PositionParamVo vo = new PositionParamVo();
        BeanUtils.copyProperties(positionParam, vo);
        vo.setPositionId(positionParam.getPosition().getId());
        vo.setPositionName(positionParam.getPosition().getName());
        Position position = positionParam.getPosition();
        vo.setPositionVo(positionService.wrap(position));
        ParameterContainer container = ParameterContainer.getInstance();
        if( vo.getBusiType() !=null){
            vo.setBusiTypeName(container.getBusinessName(SYS_BUSI_TYPE, vo.getBusiType()));
        }
        if( vo.getStatus() !=null){

            vo.setOrgTypeName(container.getBusinessName(SYS_ORGAN, vo.getOrgType()));
        }
        return vo;
    }

    @Override
    public void doCallback(PositionParam positionParam, PositionParamVo vo) {
        Position position = positionParam.getPosition();
        if (position != null) {
            vo.setPositionId(position.getId());
            vo.setPositionName(position.getName());
            vo.setPositionVo(positionService.wrap(position));
        }
        ParameterContainer container = ParameterContainer.getInstance();
        if( vo.getBusiType() !=null){
            vo.setBusiTypeName(container.getBusinessName(SYS_BUSI_TYPE, vo.getBusiType()));
        }
        if( vo.getOrgType() !=null){

            vo.setOrgTypeName(container.getBusinessName(SYS_ORGAN, vo.getOrgType()));
        }
    }
}
