package eccrm.base.position.service;


import com.ycrl.core.pager.PageVo;
import eccrm.base.position.bo.ClassifyBo;
import eccrm.base.position.domain.Classify;
import eccrm.base.position.vo.ClassifyVo;

import java.util.List;

/**
 * Generated by chenl on 2014-10-13.
 */

public interface ClassifyService /*extends VoWrapper<Classify,ClassifyVo>*/ {

    String save(Classify classify);

    void update(Classify classify);

    PageVo query(ClassifyBo bo);

    List<ClassifyVo> tree(ClassifyBo bo);

    ClassifyVo findById(String id);

    void deleteByIds(String... ids);

}
