package eccrm.base.position.service;

//import com.ycrl.core.pager.PageVo;
//import eccrm.core.VoWrapper;


import com.ycrl.core.pager.PageVo;
import eccrm.base.position.bo.PositionBo;
import eccrm.base.position.domain.Position;
import eccrm.base.position.vo.PositionVo;

import java.util.List;

/**
 * Generated by chenl on 2014-10-11.
 */

public interface PositionService {

    String save(Position position);

    void update(Position position);

    PageVo query(PositionBo bo);

    PageVo queryInclude(PositionBo bo);


    List<PositionVo> queryByOrgId(String id);

    /**
     * 岗位查询员工
     *
     * @param id
     * @return
     */
    PositionVo findById(String id);

    PositionVo findByOpId(String id);

    /**
     * 系统查询岗位接口
     *
     * @param code 系统编号
     * @return
     */
    List<PositionVo> findByCode(String code);

    /**
     * 根据岗位名称查找对应的所有员工的ID
     *
     * @param positionNames 岗位名称的可变数组
     * @return 用逗号分隔的员工ID
     */
    String findUserByPositionName(String... positionNames);

    void deleteByIds(String... ids);

    Boolean isExists(String name);

    PositionVo wrap(Position position);

    /**
     * 查询指定类型下状态为有效的岗位
     *
     * @param type 岗位类型ID
     */
    List<PositionVo> queryValidByType(String type);

    /**
     * 根据岗位编号，获得该岗位下所有的员工信息
     *
     * @return 员工ID
     */
    List<String> queryEmployeeByCode(String code);
}
