package eccrm.base.position.service;


import com.ycrl.core.beans.BeanWrapper;
import com.ycrl.core.pager.PageVo;
import eccrm.base.employee.vo.EmployeeVo;
import eccrm.base.position.bo.PositionEmpBo;
import eccrm.base.position.domain.PositionEmp;
import eccrm.base.position.vo.PositionEmpVo;

import java.util.List;

/**
 * Generated by chenl on 2014-10-18.
 */

public interface PositionEmpService extends BeanWrapper<PositionEmp, PositionEmpVo> {

    String save(PositionEmp positionEmp);

    /**
     * 保存关联关系
     * 会根据机构、岗位、员工ID进行去重
     * @param positionEmp 机构岗位对象
     */
    String saves(PositionEmp positionEmp);

    /**
     * 批量保存关联关系
     * @param orgId      组织机构id
     * @param positionId 岗位id
     * @param empIds     员工id集合
     */
    void batchSave(String orgId, String positionId, String[] empIds);

    /**
     * 批量保存关联关系 返回员工ID集合
     * @param orgId      组织机构id
     * @param positionId 岗位id
     * @param empIds     员工id集合
     */
    void batchSaveTwo(String orgId, String positionId, String[] empIds);

    void update(PositionEmp positionEmp);

    PageVo query(PositionEmpBo bo);

    PositionEmpVo findById(String id);

    void deleteByIds(String... ids);

    List<EmployeeVo> findByEmployee(String positionId, String orgId);

    /**
     * 查询岗位下员工的ID列表
     * @param positionIds 岗位ID列表
     * @return 员工ID集合
     */
    List<String> findEmployeeIds(String[] positionIds);

    /**
     * 查询岗位下员工的ID列表
     * @param positionId 岗位ID
     * @param orgId      机构ID
     * @return 员工ID集合
     */
    List<String> findEmployeeIds(String positionId, String orgId);


    /**
     * 根据员工id查询对应的岗位和机构信息
     * 不包含员工信息
     * @param empId 员工id（不可为空）
     */
    List<PositionEmpVo> queryByEmp(String empId);

    void delete(String orgId, String positionId, String[] empIds);

    /**
     * 查询指定组织下的指定岗位下的所有员工的ID
     * @param orgId         组织机构id
     * @param positionNames 岗位名称
     */
    List<EmployeeVo> queryEmployees(String orgId, String[] positionNames);

    /**
     * 分页查询指定组织机构、执行岗位下的员工信息
     * <p>注意：两个参数均不能为空，任意为空，则返回null</p>
     * @param orgId      组织机构id
     * @param positionId 岗位id
     */
    PageVo queryEmployees(String orgId, String positionId);

    @Deprecated
    List<EmployeeVo> queryAll(PositionEmpBo bo);

    List<PositionEmpVo> findByEmpId(String id);

    /**
     * 查询指定员工的所有的岗位ID集合
     * @param empId 员工id
     * @return 岗位id集合
     */
    List<String> findPositionIds(String empId);

    /**
     * 查询指定员工的所有的系统编号
     * @param empId 员工id
     * @return 系统集合
     */
    List<String> findOrgParams(String empId);

    /**
     * 查询指定员工所属的所有的组织机构的id集合
     * @param empId 员工id
     * @return 组织机构id集合
     */
    List<String> findOrgIds(String empId);
}
