package eccrm.base.position.service;


import com.ycrl.core.pager.PageVo;
import eccrm.base.position.bo.PositionParamBo;
import eccrm.base.position.domain.Position;
import eccrm.base.position.domain.PositionParam;
import eccrm.base.position.vo.PositionParamVo;

import java.util.List;

/**
 * Generated by chenl on 2014-10-20.
 */

public interface PositionParamService {

    String save(PositionParam positionParam);

    void update(PositionParam positionParam);

    PageVo query(PositionParamBo bo);

    PositionParamVo findById(String id);

    void deleteByIds(String... ids);

    /**
     * 系统查询岗位接口
     *
     * @param busiType 系统可变数组
     * @return
     */
    List<Position> findByPosition(String... busiType);

}
