package eccrm.base.role.service;

import eccrm.base.role.domain.RoleUser;
import eccrm.base.role.vo.RoleUserVo;
import eccrm.core.VoWrapper;

import java.util.List;

/**
 * Generated by miles on 2014-07-21.
 */

public interface RoleUserService extends VoWrapper<RoleUser, RoleUserVo> {

    void save(RoleUser roleUser);

    void save(String userId, String[] roleIds);

    List<RoleUserVo> queryByUserId(String userId);

    void deleteByUserId(String userId);

    void deleteByIds(String[] idArr);
}
