package eccrm.base.role.service;

import eccrm.base.menu.vo.MenuVo;

import java.util.List;

/**
 * Generated by miles on 2014-07-21.
 */

public interface RoleResourceService {

    /**
     * 根据角色id与一组资源（菜单）的id建立角色与资源的关联关系
     * 默认按照资源的id的顺序排序
     *
     * @param roleId  角色id
     * @param menuIds 资源id数组
     */
    void save(String roleId, String[] menuIds);

    /**
     * 获得一个角色下的所有资源
     *
     * @param roleId 角色id
     */
    List<MenuVo> queryByRoleId(String roleId);

    /**
     * 获得一个用户所拥有的所有资源
     * 查询当前用户、用户所属用户组对应的角色的资源
     *
     * @param userId 用户id
     * @return 资源列表
     */
    List<MenuVo> queryByUserId(String userId);

    /**
     * 根据角色id删除对应的所有资源
     *
     * @param roleId 角色id
     */
    void deleteByRoleId(String roleId);

    /**
     * 根据id删除关联关系
     *
     * @param ids id数组
     */
    void deleteByIds(String[] ids);

    /**
     * 查询用户不允许被访问的资源集合
     * 查询用户的所有角色，包括用户组的角色，然后根据角色查询所拥有的权限
     * @param userId 用户id
     * @return 资源集合，进包含资源名称、地址、编号
     */
    List<MenuVo> defendAccessResources(String userId);

}
