package eccrm.base.contact.service;

import com.ycrl.core.pager.PageVo;
import eccrm.base.contact.bo.ContactBo;
import eccrm.base.contact.domain.Contact;
import eccrm.base.contact.vo.ContactVo;

import java.util.List;

/**
 * Generated by chenl on 2014-09-22.
 */

public interface ContactService {
    /**
     * 系统参数：联络渠道
     */
    String SP_CHANNEL = "SP_CHANNEL";
    /**
     * 系统参数:联系方向
     */
    String SP_CONTACT_DIRECT = "SP_CONTACT_DIRECT";
    /**
     * 业务参数：联络事项
     */
    String BP_CONTACT_ITEM = "BP_CONTACT_ITEM";
    /**
     * 业务参数:联络结果
     */
    String BP_CONTACT_RESULT = "BP_CONTACT_RESULT";
    String BP_CONTACT_TYPE = "LL_MBLX";

    /**
     * 业务参数：客户来源
     */
    String RESOURCE_TYPE = "BP_KHLX";

    String save(Contact contact);

    void update(Contact contact);

    PageVo query(ContactBo bo);

    ContactVo findById(String id);

    List<ContactVo> findBySheetNo(String sheetNo, String nodeName);

    void deleteByIds(String... ids);

    PageVo findByIds(String[] idArr);

    /**
     * 只会更新联络信息
     * 联系人、联系人名称、联系类型
     * @param contact 联络记录
     */
    void updateResource(Contact contact);

    /**
     * 根据录音编号更新对应的联络结束时间
     * @param recordId 录音编号
     */
    void updateEndTime(String recordId);

    /**
     * 将联络记录绑定到指定工单上
     * 只会更新如下信息：业务ID、工单编号、工单类型
     * @param contact 联络记录
     */
    void updateFlow(Contact contact);
}
